// AUTHORIZATION
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const SIGN_UP = 'SIGN_UP';
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

// ORDERS
export const CREATE_ORDER = 'CREATE_ORDER';
export const NEW_ORDER_ID = 'NEW_ORDER_ID';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDER = 'FETCH_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const FETCH_ORDER_ID = 'FETCH_ORDER_ID'
export const ORDER_ERROR = 'ORDER_ERROR';
export const SORT_ORDERS = "SORT_ORDERS";
export const CLEAR_SORT_ORDERS = "CLEAR_SORT_ORDERS";
// export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';

//CLIENTS
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENT = "FETCH_CLIENT";
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const FETCH_CLIENT_ID = 'FETCH_CLIENT_ID';
export const CLIENT_ERROR = 'CLIENT_ERROR';

//LOADINGS 
export const CREATE_LOADING = 'CREATE_LOADING';
export const NEW_LOADING_ID = 'NEW_LOADING_ID';
export const FETCH_LOADINGS = 'FETCH_LOADINGS';
export const FETCH_LOADING = "FETCH_LOADING";
export const DELETE_LOADING = 'DELETE_LOADING';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const FETCH_LOADING_ID = 'FETCH_LOADING_ID';
export const LOADING_ERROR = 'LOADING_ERROR';

// UPLOADS
export const FETCH_FILES = 'FETCH_FILES';
export const UPLOAD_FILES = 'UPLOAD_FILES';
export const ADD_FILE = 'ADD_FILE';
export const REMOVE_FILE = 'REMOVE_FILE';
export const CLEAR_FILES = 'CLEAR_FILES';
export const DELETE_FILE = 'DELETE_FILE';
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const FILE_ERROR = 'FILE_ERROR';

//EVENTS
export const CLEAR_STATE = 'CLEAR_STATE';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_ACTIVE_SUB_TAB = 'SET_ACTIVE_SUB_TAB';
export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';
export const FILTER_ORDERS = 'FILTER_ORDERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// ERROR
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const SET_ERROR = 'SET_ERROR';

// MODAL
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';