// AUTHORIZATION
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// ORDERS
export const CREATE_ORDER = 'CREATE_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDER = 'FETCH_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';
export const FETCH_ORDER_ID = 'FETCH_ORDER_ID';

//CLIENTS
export const CREATE_CLIENT = 'CREATE_CLIENT';
export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENT = "FETCH_CLIENT";
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const EDIT_CLIENT = 'EDIT_CLIENT';
export const FETCH_CLIENT_ID = 'FETCH_CLIENT_ID';

//LOADINGS 
export const CREATE_LOADING = 'CREATE_LOADING';
export const FETCH_LOADINGS = 'FETCH_LOADINGS';
export const FETCH_LOADING = "FETCH_LOADING";
export const DELETE_LOADING = 'DELETE_LOADING';
export const EDIT_LOADING = 'EDIT_LOADING';
export const FETCH_LOADING_ID = 'FETCH_LOADING_ID';

//EVENTS
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';

// ERROR
export const NETWORK_ERROR = 'NETWORK_ERROR';